core/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import root, hi, hello, homework1, tag_test

urlpatterns = [
    path('hi/', root),
    path('hi/<str:w>/', hi),
    path('hi/<int:n1>/<int:n2>/', hello),
    path('r/<int:start>/<int:stop>/<int:base>/', homework1),
    path('tag_test/', tag_test),
    path('admin/', admin.site.urls),

    path('posts/', include('practice1.urls')),
]

practice1/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.show, name='show'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

practice1/models.py
from django.db import models


# Create your models here.
# ( ) => 繼承
class Post(models.Model):
    # CharField 單行文字 unique 不重複
    title = models.CharField(max_length=255, unique= True)
    # TextField 多行文字
    content = models.TextField(max_length=255)

    def __str__(self):
        return self.title

core/forms.py
from django.forms import ModelForm

class BootstrapModelForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'placeholder': '請輸入{}'.format(self.fields[field].label)
            })

practice1/forms.py
from core.forms import BootstrapModelForm

from .models import Post

class PostModelForm(BootstrapModelForm):
    class Meta:
        model = Post
        fields = '__all__'

core/views.py
from django.http import HttpResponse
from django.shortcuts import render


def root(request):
    s = '<h1>Hello World</h1>'
    return HttpResponse(s)

def hi(request,w):
    # w = request.GET.get('w')
    return HttpResponse(w)

# def hello(request,n1,n2):
#     # w = request.GET.get('w')
#     return HttpResponse('<h1>{}</h1>'.format(n1+n2))

def hello(request,n1,n2):
    s = n1 + n2
    return render(request,'test.html',{
        's':s
    })

def homework1(request, start, stop, base):
    numArray = []
    isReversed = False
    if start > stop:
        # x = start
        # start = stop
        # stop = x
        start, stop = stop, start
        isReversed = True

    rr = range(start,stop+1)
    if isReversed:
        rr = reversed(rr)

    if base == 1:
        for num in rr:
            if num%2 == 1:
                numArray.append(num)
    else:
        for num in rr:
            if num%2 == 0:
                numArray.append(num)

    return render(request,'r.html',{
        'numArray':numArray
    })

def tag_test(request):
    l = [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
    return render(request, 'tag_test.html', {
        'l': l
    })

practice1/views.py
from django.shortcuts import render, get_object_or_404, redirect

from .models import Post
from .forms import PostModelForm


# Create your views here.
def index(request):
    posts = Post.objects.all()
    return render(request, 'posts/index.html', {
        'posts': posts,
    })


def show(request, pk):
    # post = Post.objects.get(pk=pk)
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'posts/show.html', {
        'post': post
    })


def new(request):
    form = PostModelForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('posts:index')

    return render(request, 'posts/new.html', {
        'form': form
    })


def edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    form = PostModelForm(request.POST or None, instance=post)

    if form.is_valid():
        form.save()
        return redirect('posts:index')

    return render(request, 'posts/edit.html', {
        'form': form
    })


def delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('posts:index')

templates/_form.html
<form action="" method="post">
  {% csrf_token %}

  {% if form.non_field_errors %}
    <div class="alert alert-danger" style="margin-top: 10px;">
      {% for error in form.non_field_errors %}
        <strong>{{ error }}</strong>
      {% endfor %}
    </div>
  {% endif %}

  {% for field in form %}
    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text" style="min-width:100px;">{{ field.label }}</span>
      </div>
      {{ field }}
    </div>
    {% if field.errors %}
      <div class="alert alert-dismissible alert-danger fade show" style="margin-top: 10px;">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>{{ field.label }}錯誤</strong>
        {% for error in field.errors %}
          <p>{{ error }}</p>
        {% endfor %}
      </div>
    {% endif %}
  {% endfor %}

  <button type="submit" class="btn btn-info float-right">送出</button>
</form>

<style>
  textarea {
    resize: none;
  }
</style>

templates/hi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hi</title>
</head>
<body>

<h1>{{ s }}</h1>

{% if s > 60 %}
    <p>jjjjjj</p>
{% endif %}

</body>
</html>

templates/layout.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}MyDjangoWeb{% endblock %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

{#    <style>#}
{#        .container {#}
{#            margin-top: 20px;#}
{#        }#}
{#    </style>#}
</head>

<body>
    <div class="container mt-3">
        <div class="row">
            <div class="col">
                {% block main %}{% endblock %}
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

templates/posts/edit.html
{% extends "layout.html" %}

{% block title %}Edit{% endblock %}

{% block main %}
    <h1>Post Edit</h1>

{#    <form action="" method="post">#}
{#        {% csrf_token %}#}
{##}
{#        {{ form.as_p }}#}
{##}
{#        <button type="submit">Submit</button>#}
{#    </form>#}

    {% include "_form.html" %}
{% endblock %}

templates/posts/index.html
{% extends "layout.html" %}

{% block title %}Post{% endblock %}

{% block main %}

    <a class="btn btn-outline-info btm-sm float-right" href="{% url 'posts:new' %}">New Posts</a>

    <h1>Posts</h1>

    <hr>

    {% for post in posts %}
        <a href="{% url 'posts:show' post.id %}">{{ post.id }}</a> | {{ post.title }} - {{ post.content }} <br>
    {% endfor %}
{% endblock %}

templates/posts/new.html
{% extends "layout.html" %}

{% block title %}New{% endblock %}

{% block main %}
    <h1>Post New</h1>

{#    <form action="" method="post">#}
{#        {% csrf_token %}#}
{##}
{#        {{ form.as_p }}#}
{##}
{#        <button type="submit">Submit</button>#}
{#    </form>#}

    {% include "_form.html" %}
{% endblock %}

templates/posts/show.html
{% extends "layout.html" %}

{% block title %}Show{% endblock %}

{% block main %}
    <a class="btn btn-outline-info btn-sm float-right" style="margin-left: 20px; " href="{% url 'posts:edit' post.id %}">Edit</a>
    <a class="btn btn-outline-danger btn-sm float-right" href="{% url 'posts:delete' post.id %}">Delete</a>

    <h1>#{{ post.id }} - {{ post.title }}</h1>

    <hr>

    {{ post.content }}

    <hr>

    <a href="{% url 'posts:index' %}"><< Back to list</a>
{% endblock %}

templates/r.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Homework</title>
</head>
<body>


<ul>
    {% for i in numArray %}
        <li>{{ i }}</li>
    {% endfor %}

    {# this is commit #}
</ul>


</body>
</html>

templates/tag_test.html
{{ l | join:"˙ ˙" }}

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test</title>
</head>
<body>

<h1>{{ s }}</h1>

{% if s > 60 %}
    <p>合格</p>
{% endif %}

</body>
</html>